# Generated by Django 5.0.1 on 2024-04-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_registration_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_fee',
        ),
    ]
