# Generated by Django 5.0.1 on 2024-05-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
