# Generated by Django 5.0.1 on 2024-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fee',
            field=models.IntegerField(verbose_name='Registration Fee'),
        ),
    ]
