# Generated by Django 5.0.1 on 2024-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_myclubuser_event_alter_myclubuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Capacity'),
        ),
    ]
